### ISSUE TITLE
Question: Why install Knative on EKS Fargate?

### ISSUE THREAD

**Issue by shuknk8s** [mreferre/knative-on-fargate#2]
EKS Fargate itself offers natively serving capabilities with scale 0-N-0(FaaS) then what is the motivation of installing Knative on EKS Fargate. It makes complete sense to bring in FaaS capabilities on EKS by installing Knative on top of it but I dont see any value of installing Knative on EKS Fargate. Let me know your motivation which is not clear from this post or I am missing something.

**Comment by mreferre** [comment]
Hi @shuknk8s thanks for the question. The whole point for me was to show how Fargate and Knative are complementary in nature and not alternatives. Last I checked Kubernetes did not offer scale to 0 for a `service` and hence the need for Knative. I know there have been discussions lately about adding that capability (scale to 0) to the vanilla HPA but I am not sure it's available yet? Also if you think of Knative simply as "scale to 0" and that is coming to native HPA I am wondering if your question shouldn't be extended to "why Knative at all?". I see Knative doing more than just scaling to 0 (e.g. eventing). 

All in all what Fargate does is allowing you to not having to deal with a cluster of worker nodes (and so not having to deal with Cluster Autoscaler etc). So in a way it removes a bunch of very infrastructure related things you have to do (below the K8s line). I see Knative trying to add value above the K8s line.

**Comment by shuknk8s** [comment]
Thanks for the quick turnaround.

EKS fargate is the serverless FaaS platform  built on top of kubernetes
similar to GCP Google Cloud Run which has the serving based on volume of
request and scale to zero  capability built in.

Knative is an excellent unified CaaS, FaaS  and PaaS  platform for
Kubernetes so Knative is good choice for EKS on EC2 not for EKS Fargate
which already has serving and FaaS capability built in which offers scale
to N and scale down to zero . I did not mention vanilla kubernetes offers
scale down to zero capability but kubernets FaaS platform like Google Cloud
Run , AWS EKS Fargate and Azure ACI offer that capability out of the box.

Link below for your review

https://thenewstack.io/comparison-aws-fargate-vs-google-cloud-run-vs-azure-container-instances/

**Comment by mreferre** [comment]
I think your definition of EKS/Fargate is a bit off. EKS/Fargate is most definitely NOT a "serverless FaaS platform built on top of K8s". EKS/Fargate is a specific "compute" configuration that allows you to limit infrastructure related work. The whole purpose of Fargate is to help with what's "under K8s" not adding anything "on top of K8s". EKS/Fargate does not have any specific "serving" capabilities other than what K8s provides on its own (and that could work with EC2 as well). We tried to make it clear when we [announced it at re:Invent back in 2019](https://www.youtube.com/watch?v=m-3tMXmWWQw) but we know there is still quite a bit of confusion.

**Comment by shuknk8s** [comment]
Pardon my ignorance on EKS Fargate.

Thanks for the clarification and it did help me to make an informed
decision that Google Cloud Run is way better alternative compared to EKS
fargate purely from  feature standpoint,  it is indeed a FaaS and I know
for sure it is serverless, has serving in built and scale up to N and down
to zero based on request load. Google Cloud is knative implementation on
GKE running serverless

**Comment by shuknk8s** [comment]
Also I am a Knative Community contributor so I am aware that Knative is
more than just Serving and serving itself is not scale up to N and back to
zero but service config, revision , routing  blue green , Canary deployment
etc apart from eventing.

**Comment by mreferre** [comment]
It's always hard to compare these products but If you are looking for an AWS service that is somewhat comparable to Google Cloud Run that would be https://aws.amazon.com/apprunner/.

**Comment by shuknk8s** [comment]
Nice , glad to know that. Let me explore this service as it is difficult to
even navigate myriad of aws services and the count is only increasing.
Google Cloud Run and Google Cloud Run on GKE are commercial implementation
of Knative on GKE  which implements both CaaS and FaaS under the same hood.

GKE is by far the best Kubernetes offering from feature and developer
advocacy standpoint as per my experience. Again this is my personal opinion
based on experience with EKS on EC2, GKE and AKS.

**Comment by mreferre** [comment]
The good thing about opinions is that there are many of them :) 

Thanks.

**Comment by shuknk8s** [comment]
Cool, thanks!  That's why I mentioned  " my own opinion" and there are many
similar opinions similar to my opinions. Anyway it was nice connecting with
you and enjoyed the exchanges. If you are interested you can take a look at
riff , vendor neutral Knative implemention on Kubernetes.
