### ISSUE TITLE
"These instructions" returns a 404

### ISSUE THREAD

**Issue by iiian** [mreferre/knative-on-fargate#3]
Can you check if you're getting the same issue? Seems knative might have moved them.

**Comment by iiian** [comment]
Oh, to be more explicit, "these instructions" refers to the variety of links under the same label in the main README.

**Comment by mreferre** [comment]
Oh it looks like they moved stuff around. It linked to `https://knative.dev/docs/install/knative-with-gloo/`. Let me see where they put these docs...

**Comment by mreferre** [comment]
Update: found a backup @ https://prstaging--knative-v1.netlify.app/docs/install/knative-with-gloo/ 

Still trying to figure out where this went. It looks like that now the Knative web site only lists installing with the knative CLI.

**Comment by iiian** [comment]
All good. I was able to find back up links as well, just thought I'd alert you! Thanks!

**Comment by mreferre** [comment]
Thanks Ian. Appreciated. 

Looks like there wasn't much interest in Gloo+Knative so these docs have been left behind (https://twitter.com/cgaunerd/status/1509155277878222858). I will probably need to update the repo to call this out.

**Comment by mreferre** [comment]
Update: now it looks like the backup page itself (https://prstaging--knative-v1.netlify.app/docs/install/knative-with-gloo/) is no longer available. It also seems that [this page](https://docs.solo.io/gloo-edge/1.7.23/installation/knative/) is saying `Gloo Edge Knative Ingress is deprecated in 1.10 and will not be available in 1.11`.
